name: Build Julia
description: Build Julia from source for a given commit.
author: Sascha Mann

branding:
  icon: cpu
  color: purple

inputs:
  ref:
    description: Value passed to git checkout.
    default: master
    required: false
  source-repo:
    description: Value passed to git clone.
    default: https://github.com/JuliaLang/julia.git
    required: false

runs:
  using: composite
  steps:
    - name: Clone Julia
      run: git clone ${{ inputs.source-repo }} "$HOME/julia"
      shell: bash
    
    - name: Checkout ref
      run: |
        cd "$HOME/julia"
        git checkout ${{ inputs.ref }}
      shell: bash

    - name: Build Julia
      run: |
        cd "$HOME/julia"
        make -j 2
      shell: bash
    
    - name: Print Version
      run: |
        cd "$HOME/julia"
        ./julia --version
      shell: bash
