name: Example builds

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        julia-ref: [v1.5.3]

    steps:
      - uses: actions/checkout@v2

      - name: Build Julia
        uses: ./
        with:
          ref: ${{ matrix.julia-ref }}

      - name: Show versioninfo()
        run: ~/julia/julia -e "using InteractiveUtils; versioninfo()"
