name: Example builds

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        julia-ref: [v1.5.3]

    steps:
      - uses: actions/checkout@v2

      - name: Cache
        id: cache-julia
        uses: actions/cache@v2
        with:
          path: ~/julia
          # Note that this cache key will not work with branches
          # because there could be new commits after the cache has been created
          key: ${{ runner.os }}-${{ matrix.julia-ref }}

      - name: Build Julia
        if: steps.cache-julia.outputs.cache-hit != 'true'
        uses: ./ # replace this with julia-actions/build-julia@v1 in your workflows
        with:
          ref: ${{ matrix.julia-ref }}

      - name: Show versioninfo()
        run: ~/julia/julia -e "using InteractiveUtils; versioninfo()"
